fix: isolating with single quotes
Signed-off-by: matttrach <matttrach@gmail.com>

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -66,21 +66,18 @@ jobs:
       - name: Apply
         if: steps.release-please.outputs.release_created
         shell: bash
-        env:
-          AGE_SECRET_KEY: ${{secrets.AGE_SECRET_KEY}}
-          B64_SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
         run: |
           echo "Setting up env..."
-          if [ "" = "$AGE_SECRET_KEY" ]; then echo "Missing encrypt key, please run repo setup before release."; exit 1; fi
-          if [ "" = "$B64_SSH_PRIVATE_KEY" ]; then echo "Missing CI ssh access key, please run repo setup before release."; exit 1; fi
+          if [ "" = '${{secrets.AGE_SECRET_KEY}}' ]; then echo "Missing encrypt key, please run repo setup before release."; exit 1; fi
+          if [ "" = '${{secrets.SSH_PRIVATE_KEY}}' ]; then echo "Missing CI ssh access key, please run repo setup before release."; exit 1; fi
           if [ ! -f age_recipients.txt ]; then echo "Missing encryption recipients, please run repo setup before release."; exit 1; fi
           if [ ! -f terraform.tfstate.age ]; then echo "Missing initial encrypted terraform state, please run repo setup before release."; exit 1; fi
           eval "$(ssh-agent -s)"
-          echo $B64_SSH_PRIVATE_KEY
-          SSH_PRIVATE_KEY="$(echo "$B64_SSH_PRIVATE_KEY" | base64 -d)"
+          SSH_PRIVATE_KEY="$(echo '${{secrets.SSH_PRIVATE_KEY}}' | base64 -d)"
           ssh-add <<< "$SSH_PRIVATE_KEY"
-          TERRAFORM_STATE_AGE="$(base64 -d terraform.tfstate.age)"
-          echo '${{secrets.AGE_SECRET_KEY}}' | age -d -i - -o terraform.tfstate <<< "$TERRAFORM_STATE_AGE"
+          base64 -d terraform.tfstate.age > terraform.tfstate.age.dc
+          echo '${{secrets.AGE_SECRET_KEY}}' | age -d -i - -o terraform.tfstate terraform.tfstate.age.dc
+          rm -f terraform.tfstate.age.dc
           export TF_VAR_ip="${{ steps.ip.outputs.ipv4 }}"
           echo "Starting  deploy..."
           terraform init
diff --git a/.github/workflows/update.yaml b/.github/workflows/update.yaml
--- a/.github/workflows/update.yaml
+++ b/.github/workflows/update.yaml
@@ -47,20 +47,20 @@ jobs:
         id: ip
       - name: update
         shell: bash
-        env:
-          AGE_SECRET_KEY: secrets.AGE_SECRET_KEY
-          B64_SSH_PRIVATE_KEY: secrets.SSH_PRIVATE_KEY
         run: |
-          if [ "" = "$AGE_SECRET_KEY" ]; then echo "Missing encrypt key, please run repo setup before update."; exit 1; fi
-          if [ "" = "$B64_SSH_PRIVATE_KEY" ]; then echo "Missing CI ssh access key, please run repo setup before update."; exit 1; fi
-          if [ ! -f age_recipients.txt ]; then echo "Missing encryption recipients, please run repo setup before update."; exit 1; fi
-          if [ ! -f terraform.tfstate.age ]; then echo "Missing initial encrypted terraform state, please run repo setup before update."; exit 1; fi
+          echo "Setting up env..."
+          if [ "" = '${{secrets.AGE_SECRET_KEY}}' ]; then echo "Missing encrypt key, please run repo setup before release."; exit 1; fi
+          if [ "" = '${{secrets.SSH_PRIVATE_KEY}}' ]; then echo "Missing CI ssh access key, please run repo setup before release."; exit 1; fi
+          if [ ! -f age_recipients.txt ]; then echo "Missing encryption recipients, please run repo setup before release."; exit 1; fi
+          if [ ! -f terraform.tfstate.age ]; then echo "Missing initial encrypted terraform state, please run repo setup before release."; exit 1; fi
           eval "$(ssh-agent -s)"
-          SSH_PRIVATE_KEY="$(echo "$B64_SSH_PRIVATE_KEY" | base64 -d)"
+          SSH_PRIVATE_KEY="$(echo '${{secrets.SSH_PRIVATE_KEY}}' | base64 -d)"
           ssh-add <<< "$SSH_PRIVATE_KEY"
-          TERRAFORM_STATE_AGE="$(base64 -d terraform.tfstate.age)"
-          echo '${{secrets.AGE_SECRET_KEY}}' | age -d -i - -o terraform.tfstate <<< "$TERRAFORM_STATE_AGE"
+          base64 -d terraform.tfstate.age > terraform.tfstate.age.dc
+          echo '${{secrets.AGE_SECRET_KEY}}' | age -d -i - -o terraform.tfstate terraform.tfstate.age.dc
+          rm -f terraform.tfstate.age.dc
           export TF_VAR_ip="${{ steps.ip.outputs.ipv4 }}"
+          echo "Starting  deploy..."
           terraform init
           # manage the security group rule for the terraform runner as a separate entity to prevent dependency chain issues with server object
           if [ "" = "$(terraform state list | grep 'module.aws_rke2_rhel9_rpm.module.aws_access.module.security_group.aws_vpc_security_group_egress_rule.to_ip[0]')" ]; then
@@ -72,6 +72,7 @@ jobs:
           terraform apply --auto-approve || true
           sleep 5
           terraform apply --auto-approve || true
+          echo "Saving state..."
           rm -rf terraform.tfstate.age && age -e -R age_recipients.txt -o terraform.tfstate.age terraform.tfstate && rm -f terraform.tfstate
           base64 terraform.tfstate.age > tmp_terraform.tfstate.age
           mv tmp_terraform.tfstate.age terraform.tfstate.age
