fix: fail early without admin key
Signed-off-by: matttrach <matttrach@gmail.com>

diff --git a/.github/workflows/rotate_ci_age_key.yaml b/.github/workflows/rotate_ci_age_key.yaml
--- a/.github/workflows/rotate_ci_age_key.yaml
+++ b/.github/workflows/rotate_ci_age_key.yaml
@@ -41,6 +41,7 @@ jobs:
       - name: 'Rotate CI AGE Key'
         run: |
           echo "Rotating AGE key for the CI..."
+          if [ -z "$GITHUB_TOKEN" ]; then echo "token not found, please make sure to add ADMIN_GITHUB_TOKEN to secrets"; exit 1; fi
           if [ "" = '${{secrets.AGE_SECRET_KEY}}' ]; then echo "Missing encrypt key."; exit 1; fi
 
           echo "Decrypt files..."
