fix: validate all secrets are in place for setup, update docs to add token, remove secrets before commit
Signed-off-by: matttrach <matttrach@gmail.com>

diff --git a/.github/workflows/setup_repo.yaml b/.github/workflows/setup_repo.yaml
--- a/.github/workflows/setup_repo.yaml
+++ b/.github/workflows/setup_repo.yaml
@@ -56,6 +56,26 @@ jobs:
           echo "Setting up Repo..."
           if [ -z "$GITHUB_TOKEN" ]; then echo "token not found, please make sure to add ADMIN_GITHUB_TOKEN to secrets"; exit 1; fi
           if [ -z "${{vars.AWS_AUTH}}" ]; then echo "AWS auth type not found, please specify AWS_AUTH action variable as either 'OIDC' or 'IAM'"; exit 1; fi
+          if [ "${{vars.AWS_AUTH}}" = "IAM" ]; then
+            if [ -z "${{secrets.AWS_ACCESS_KEY_ID}}" ]; then
+              echo "AWS_ACCESS_KEY_ID secret not found, please make sure to add it to the repo action secrets";
+              exit 1;
+            fi
+            if [ -z "${{secrets.AWS_SECRET_ACCESS_KEY}}" ]; then
+              echo "AWS_SECRET_ACCESS_KEY secret not found, please make sure to add it to the repo action secrets";
+              exit 1;
+            fi
+          fi
+          if [ "${{vars.AWS_AUTH}}" = "OIDC" ]; then
+            if [ -z "${{secrets.AWS_ROLE}}" ]; then
+              echo "AWS_ROLE secret not found, please make sure to add it to the repo action secrets";
+              exit 1;
+            fi
+          fi
+          if [ -z "secrets.AWS_REGION" ]; then
+            echo "AWS_REGION secret not found, please make sure to add it to the repo action secrets";
+            exit 1;
+          fi
           git config --global user.name 'automation'
           git config --global user.email 'automation@users.noreply.github.com'
           git remote set-url origin "https://x-access-token:$GITHUB_TOKEN@github.com/${{github.repository}}"
@@ -64,7 +84,7 @@ jobs:
           while read -r file; do
             if [ -f "$file.age" ]; then
               if [ -n "${{secrets.AGE_SECRET_KEY}}" ]; then
-                echo '${{secrets.AGE_SECRET_KEY}}' | age -d -i - -o "$file" "$file.age"
+                echo '${{secrets.AGE_SECRET_KEY}}' | age -d -i - -o "$file" "$file.age" || true
               fi
             fi
           done <secret_file_list.txt
@@ -107,7 +127,7 @@ jobs:
           
           cd ${{github.workspace}}
 
-          echo "Saving initial states..."
+          echo "Setting initial states..."
           for lc in phase_1_project_access phase_2_ci_access phase_3_prototype phase_4_servers; do
             cd ${{github.workspace}}/$lc
             if [ ! -f terraform.tfstate ]; then
@@ -118,6 +138,15 @@ jobs:
             git add ${{github.workspace}}/$lc/terraform.tfstate.age
           done
 
+          echo "Removing secret files..."
+          cd ${{github.workspace}}
+          while read -r file; do
+            if [ -f "$file" ]; then
+              rm -f "$file";
+            fi
+          done <secret_file_list.txt
+
+          echo "Saving state..."
           if [ -n "$(git diff)" ]; then
             git commit -s -m "Setup https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
             git push origin main
