fix: use different aws auth based on secrets config (#110)
* fix: use different aws auth based on secrets config

Signed-off-by: matttrach <matttrach@gmail.com>

* fix: switch using new aws_auth var

Signed-off-by: matttrach <matttrach@gmail.com>

---------

Signed-off-by: matttrach <matttrach@gmail.com>

diff --git a/.github/workflows/setup.yaml b/.github/workflows/setup.yaml
--- a/.github/workflows/setup.yaml
+++ b/.github/workflows/setup.yaml
@@ -8,8 +8,6 @@ on:
 permissions: write-all
 
 env:
-  AWS_REGION: us-west-1
-  AWS_ROLE: ${{ secrets.AWS_ROLE }}
   GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
   GH_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
   GITHUB_OWNER: ${{ github.repository_owner }}
@@ -39,22 +37,26 @@ jobs:
             --keep AWS_SESSION_TOKEN \
             --keep TERM \
             ${{ github.workspace }}
+      # if using OICD auth
       - uses: aws-actions/configure-aws-credentials@v4
+        if: ${{vars.AWS_AUTH == 'OIDC'}}
         with:
-          role-to-assume: ${{env.AWS_ROLE}}
+          role-to-assume: ${{secrets.AWS_ROLE}}
           role-session-name: ${{github.job}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}
-          aws-region: ${{env.AWS_REGION}}
-      # example using simple auth keys
-      # - uses: aws-actions/configure-aws-credentials@v4
-      #   with:
-      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-      #     aws-region: ${{env.AWS_REGION}}
+          aws-region: ${{secrets.AWS_REGION}}
+      # if using access key auth
+      - uses: aws-actions/configure-aws-credentials@v4
+        if: ${{vars.AWS_AUTH == 'IAM'}}
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{secrets.AWS_REGION}}
       - uses: haythem/public-ip@v1.3
         id: ip
       - run: |
           echo "Setting up Repo..."
           if [ -z "$GITHUB_TOKEN" ]; then echo "token not found, please make sure to add ADMIN_GITHUB_TOKEN to secrets"; exit 1; fi
+          if [ -z "${{vars.AWS_AUTH}}" ]; then echo "AWS auth type not found, please specify AWS_AUTH action variable as either 'OIDC' or 'IAM'"; exit 1; fi
           KEY="$(age-keygen 2>/dev/null | grep '^AGE')"
           echo "$KEY" | age-keygen -y > age_recipients.txt
           gh secret set AGE_SECRET_KEY --body "$KEY"
